// challenge_vectors_gen writes the shared ComputeChallenge test vectors.
//
// Usage:
//
//	challenge_vectors_gen <challenge_vectors.json>
//
// Keys are real ML-DSA-65 public keys derived from fixed seeds, so the output is reproducible.
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"github.com/cloudflare/circl/sign/mldsa/mldsa65"

	pqc "github.com/PeculiarVentures/pqc-ratchet/go/pqcratchet"
)

type Vector struct {
	ServerSigningPub string `json:"serverSigningPub"`
	ClientSigningPub string `json:"clientSigningPub"`
	Pin              string `json:"pin"`
}

type File struct {
	Description string   `json:"description"`
	Vectors     []Vector `json:"vectors"`
}

func main() {
	if len(os.Args) != 2 {
		fatalf("usage: challenge_vectors_gen <challenge_vectors.json>")
	}
	if err := generate(os.Args[1]); err != nil {
		fatalf("generate: %v", err)
	}
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}

// pubKey derives the i-th ML-DSA-65 public key from seed SHA-256("challenge_vectors_gen/<i>").
func pubKey(i int) []byte {
	seed := sha256.Sum256([]byte(fmt.Sprintf("challenge_vectors_gen/%d", i)))
	pub, _ := mldsa65.NewKeyFromSeed(&seed)
	return pqc.DSAPublicKeyBytes(pub)
}

func vector(server, client []byte) Vector {
	return Vector{
		ServerSigningPub: hex.EncodeToString(server),
		ClientSigningPub: hex.EncodeToString(client),
		Pin:              pqc.ComputeChallenge(server, client),
	}
}

func generate(path string) error {
	var vs []Vector
	next := 0
	key := func() []byte { next++; return pubKey(next - 1) }

	// Plain pairs, each also emitted swapped to show argument order matters.
	for i := 0; i < 3; i++ {
		s, c := key(), key()
		fwd, rev := vector(s, c), vector(c, s)
		if fwd.Pin == rev.Pin {
			return fmt.Errorf("swapped pair %d has the same PIN", i)
		}
		vs = append(vs, fwd, rev)
	}

	// Search the seed sequence for a pair whose PIN has a leading zero.
	for {
		s, c := key(), key()
		if v := vector(s, c); strings.HasPrefix(v.Pin, "0") {
			vs = append(vs, v)
			break
		}
		if next > 10_000 {
			return fmt.Errorf("no leading-zero PIN found")
		}
	}

	out, err := json.MarshalIndent(File{
		Description: `pqcratchet pairing-code vectors (generated by go/cmd/challenge_vectors_gen; do not edit). ` +
			`thumb(k) = SHA-256(k); digest = SHA-256("pqcratchet/v1/Challenge" || thumb(serverSigningPub) || thumb(clientSigningPub)); ` +
			`pin = big-endian uint64(digest[0:8]) mod 1000000, zero-padded to 6 digits. Keys are hex-encoded ML-DSA-65 public keys; ` +
			`vectors 0/1, 2/3 and 4/5 are the same key pair with server and client swapped.`,
		Vectors: vs,
	}, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(out, '\n'), 0o644)
}
