// challenge_vectors_gen writes the shared ComputeChallenge and ComputeChallengeV2 test vectors.
//
// Usage:
//
//	challenge_vectors_gen pqcratchet/testdata
//
// It writes challenge_vectors.json and challenge_v2_vectors.json into that directory.
// Keys are real ML-DSA-65 public keys and nonces are derived from fixed seeds, so the output is reproducible.
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/cloudflare/circl/sign/mldsa/mldsa65"

	pqc "github.com/PeculiarVentures/pqc-ratchet/go/pqcratchet"
)

// swapPairs is how many key pairs are emitted twice, once per argument order.
const swapPairs = 3

type Vector struct {
	ServerSigningPub string `json:"serverSigningPub"`
	ClientSigningPub string `json:"clientSigningPub"`
	Pin              string `json:"pin"`
}

type File struct {
	Description string   `json:"description"`
	Vectors     []Vector `json:"vectors"`
}

func main() {
	if len(os.Args) != 2 {
		fatalf("usage: challenge_vectors_gen <testdata dir>")
	}
	dir := os.Args[1]
	if err := generate(filepath.Join(dir, "challenge_vectors.json")); err != nil {
		fatalf("generate v1: %v", err)
	}
	if err := generateV2(filepath.Join(dir, "challenge_v2_vectors.json")); err != nil {
		fatalf("generate v2: %v", err)
	}
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}

// pubKey derives the i-th ML-DSA-65 public key from seed SHA-256("challenge_vectors_gen/<i>").
func pubKey(i int) []byte {
	seed := sha256.Sum256([]byte(fmt.Sprintf("challenge_vectors_gen/%d", i)))
	pub, _ := mldsa65.NewKeyFromSeed(&seed)
	return pqc.DSAPublicKeyBytes(pub)
}

// swapPairList renders the swapped vector indices, e.g. "0/1, 2/3 and 4/5".
func swapPairList() string {
	pairs := make([]string, swapPairs)
	for i := range pairs {
		pairs[i] = fmt.Sprintf("%d/%d", 2*i, 2*i+1)
	}
	if len(pairs) == 1 {
		return pairs[0]
	}
	return strings.Join(pairs[:len(pairs)-1], ", ") + " and " + pairs[len(pairs)-1]
}

func vector(server, client []byte) Vector {
	return Vector{
		ServerSigningPub: hex.EncodeToString(server),
		ClientSigningPub: hex.EncodeToString(client),
		Pin:              pqc.ComputeChallenge(server, client),
	}
}

func generate(path string) error {
	var vs []Vector
	next := 0
	key := func() []byte { next++; return pubKey(next - 1) }

	// Plain pairs, each also emitted swapped to show argument order matters.
	for i := 0; i < swapPairs; i++ {
		s, c := key(), key()
		fwd, rev := vector(s, c), vector(c, s)
		if fwd.Pin == rev.Pin {
			return fmt.Errorf("swapped pair %d has the same PIN", i)
		}
		vs = append(vs, fwd, rev)
	}

	// Search the seed sequence for a pair whose PIN has a leading zero.
	for {
		s, c := key(), key()
		if v := vector(s, c); strings.HasPrefix(v.Pin, "0") {
			vs = append(vs, v)
			break
		}
		if next > 10_000 {
			return fmt.Errorf("no leading-zero PIN found")
		}
	}

	return writeJSON(path, File{
		Description: `pqcratchet pairing-code vectors (generated by go/cmd/challenge_vectors_gen; do not edit). ` +
			`thumb(k) = SHA-256(k); digest = SHA-256("pqcratchet/v1/Challenge" || thumb(serverSigningPub) || thumb(clientSigningPub)); ` +
			`pin = big-endian uint64(digest[0:8]) mod 1000000, zero-padded to 6 digits. Keys are hex-encoded ML-DSA-65 public keys; ` +
			"vectors " + swapPairList() + " are the same key pair with server and client swapped.",
		Vectors: vs,
	})
}

func writeJSON(path string, v any) error {
	out, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(out, '\n'), 0o644)
}

type VectorV2 struct {
	Note             string `json:"note"`
	ServerSigningPub string `json:"serverSigningPub"`
	ClientSigningPub string `json:"clientSigningPub"`
	ClientNonce      string `json:"clientNonce"`
	ServerNonce      string `json:"serverNonce"`
	Commit           string `json:"commit"`
	Pin              string `json:"pin"`
}

type FileV2 struct {
	Description string     `json:"description"`
	Vectors     []VectorV2 `json:"vectors"`
}

// nonce derives the i-th challenge nonce as SHA-256("challenge_vectors_gen/nonce/<i>").
func nonce(i int) []byte {
	n := sha256.Sum256([]byte(fmt.Sprintf("challenge_vectors_gen/nonce/%d", i)))
	return n[:]
}

func vectorV2(note string, server, client, clientNonce, serverNonce []byte) (VectorV2, error) {
	commit, err := pqc.CommitChallengeNonce(client, clientNonce)
	if err != nil {
		return VectorV2{}, err
	}
	pin, err := pqc.ComputeChallengeV2(server, client, clientNonce, serverNonce)
	if err != nil {
		return VectorV2{}, err
	}
	return VectorV2{
		Note:             note,
		ServerSigningPub: hex.EncodeToString(server),
		ClientSigningPub: hex.EncodeToString(client),
		ClientNonce:      hex.EncodeToString(clientNonce),
		ServerNonce:      hex.EncodeToString(serverNonce),
		Commit:           hex.EncodeToString(commit),
		Pin:              pin,
	}, nil
}

func generateV2(path string) error {
	a, b, c, d := pubKey(0), pubKey(1), pubKey(2), pubKey(3)
	cn, sn := nonce(0), nonce(1)

	cases := []struct {
		note                           string
		server, client, cNonce, sNonce []byte
	}{
		{"base", a, b, cn, sn},
		{"vector 0 with server and client keys swapped", b, a, cn, sn},
		{"vector 0 with only serverNonce changed", a, b, cn, nonce(2)},
		{"vector 0 with only clientNonce changed", a, b, nonce(3), sn},
		{"independent key pair and nonces", c, d, nonce(4), nonce(5)},
	}
	var vs []VectorV2
	for _, k := range cases {
		v, err := vectorV2(k.note, k.server, k.client, k.cNonce, k.sNonce)
		if err != nil {
			return err
		}
		vs = append(vs, v)
	}
	if vs[1].Pin == vs[0].Pin || vs[1].Commit == vs[0].Commit {
		return fmt.Errorf("swapped keys give the same PIN or commit")
	}
	if vs[2].Pin == vs[0].Pin || vs[2].Commit != vs[0].Commit {
		return fmt.Errorf("serverNonce-only change must keep the commit and change the PIN")
	}
	if vs[3].Pin == vs[0].Pin || vs[3].Commit == vs[0].Commit {
		return fmt.Errorf("clientNonce-only change must change the commit and the PIN")
	}

	// Search the serverNonce sequence for a PIN with a leading zero.
	for i := 6; ; i++ {
		if i > 10_000 {
			return fmt.Errorf("no leading-zero PIN found")
		}
		v, err := vectorV2("leading-zero PIN", a, b, cn, nonce(i))
		if err != nil {
			return err
		}
		if strings.HasPrefix(v.Pin, "0") {
			vs = append(vs, v)
			break
		}
	}

	return writeJSON(path, FileV2{
		Description: `pqcratchet commit-then-reveal pairing-code vectors (generated by go/cmd/challenge_vectors_gen; do not edit). ` +
			`thumb(k) = SHA-256(k); commit = SHA-256("pqcratchet/v1/Commit" || thumb(clientSigningPub) || clientNonce); ` +
			`digest = SHA-256("pqcratchet/v1/Challenge2" || thumb(serverSigningPub) || thumb(clientSigningPub) || clientNonce || serverNonce); ` +
			`pin = big-endian uint64(digest[0:8]) mod 1000000, zero-padded to 6 digits. ` +
			`Keys are hex-encoded ML-DSA-65 public keys; nonces are 32 bytes, hex-encoded.`,
		Vectors: vs,
	})
}
